config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => "public_show"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages
  resources :sections
  resources :admin_users, :except => [:show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

 <div class="form-group">
    <%= f.label(:name, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.text_field(:name, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <%= f.label(:subject_id, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.select(:subject_id, @subjects.map {|s| [s.name, s.id]}, {}, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <%= f.label(:permalink, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.text_field(:permalink, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <%= f.label(:position, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.select(:position, 1..@page_count, {}, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <div class="checkbox">
            <label>
            <%= f.check_box(:visible) %> Visible
            </label>
        </div>
    </div>
</div>

app/views/pages/edit.html.erb
<% @page_title = "Edit Page" %>

<div class="row">
<div class="col-md-11">

    <h2><%= @page_title %></h2>

    <%= form_for(@page, :url => page_path(@page, :subject_id => @subject.id), :html => {:class => "form-horizontal"}) do |f|%>

        <%= render(:partial => "form", :locals => {:f => f}) %>

        <div class="col-md-10 col-md-offset-2">
            <%= f.submit("Save", :class => "btn btn-primary") %>
            <%= link_to("Cancel", pages_path(:subject_id => @subject.id), :class => "btn btn-default") %>
        </div>

    <% end %>

</div>
</div>

app/views/pages/index.html.erb
<% @page_title = "Pages" %>

<h2>Pages</h2>
<a href=<%= new_page_path(:subject_id => @subject.id) %> class="btn btn-primary" role="button">Add New</a>

<div class="row">

<table class="table table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Page</th>
        <th>Permalink</th>
        <th>Visible</th>
        <th>Subject</th>
        <th>Sections</th>
        <th>Actions</th>
    </tr>
    </thead>

    <tbody>

    <% @pages.each do |page| %>
    <tr>
        <td><%= page.position %></td>
        <td>
            <%= link_to(page.name, page_path(page, :subject_id => @subject.id), :data => {:toggle => "tooltip", :placement => "top"}, :title => "Detail") %>
        </td>
        <td><%= page.permalink %></td>
        <td><%= status_tag(page.visible) %></td>
        <td><%= page.subject.name %></td>
        <td>
            <%= link_to(pluralize(page.sections.size, 'Section'), sections_path(:page_id => page.id), :data => {:toggle => "tooltip", :placement => "top"}, :title => "Sections") %>
        </td>
        <td>
            <%= edit_button_for(edit_page_path(page, :subject_id => @subject.id)) %>
            <%= delete_button_for(page, page_path(page, :subject_id => @subject.id)) %>
        </td>
    </tr>
    <% end %>

    </tbody>
</table>

</div>

app/views/pages/new.html.erb
<% @page_title = "Create Page" %>

<div class="row">
<div class="col-md-11">

    <h2><%= @page_title %></h2>

    <%= form_for(@page, :url => pages_path(:subject_id => @subject.id), :html => {:class => "form-horizontal"}) do |f|%>

        <%= render(:partial => "form", :locals => {:f => f}) %>

        <div class="col-md-10 col-md-offset-2">
            <%= f.submit("Save", :class => "btn btn-primary") %>
            <%= link_to("Cancel", pages_path(:subject_id => @subject.id), :class => "btn btn-default") %>
        </div>

    <% end %>

</div>
</div>

app/views/pages/show.html.erb
<% @page_title = @page.name %>

<div class="row">
<div class="col-md-8">

<h2><%= @page_title %></h2>

<dl class="dl-horizontal">

    <dt>#</dt>
    <dd><%= @page.position %></dd>

    <dt>Name</dt>
    <dd><%= @page.name %></dd>

    <dt>Permalink</dt>
    <dd><%= @page.permalink %></dd>

    <dt>Visible</dt>
    <dd><%= @page.visible ? "Yes" : "No" %></dd>

    <dt>Subject</dt>
    <dd><%= @page.subject.name %></dd>

    <dt>Pages</dt>
    <dd><%= pluralize(@page.sections.size, 'Section') %></dd>

    <dt>Created</dt>
    <dd><%= @page.created_at.to_s(:long) %></dd>

    <dt>Updated</dt>
    <dd><%= @page.updated_at.to_s(:long) %></dd>

</dl>

</div>
</div>