config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => "public_show"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages
  resources :sections
  resources :admin_users, :except => [:show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord

    acts_as_list

    has_many :pages

    scope :visible, lambda { where(:visible => true) }
    scope :invisible, lambda { where(:visible => false) }
    scope :sorted, lambda { order(:position) }
    scope :newest_first, lambda { order(:created_at => :desc) }
    scope :search, lambda { |query| where(["name LIKE ?", "%#{query}%"]) }

    validates_presence_of :name
    validates_length_of :name, :maximum => 255
    
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout "admin"
  before_action :confirm_logged_in
  
  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
    @subject_count = Subject.count + 1
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:notice] = "Subject '#{@subject.name}' created successfully."
      redirect_to(subjects_path)
    else
      @subject_count = Subject.count + 1
      render("new")
    end
  end

  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end

  def update
    @subject = Subject.find(params[:id])

    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject updated successfully."
      redirect_to(subject_path(@subject))
    else
      @subject_count = Subject.count
      render("edit")
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully."
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end
  
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

 <div class="form-group">
    <%= f.label(:name, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.text_field(:name, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <%= f.label(:position, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.select(:position, 1..@subject_count, {}, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <div class="checkbox">
            <label>
            <%= f.check_box(:visible) %> Visible
            </label>
        </div>
    </div>
</div>

app/views/subjects/delete.html.erb
<% @page_title = "Delete Subject" %>

<div class="row">
<div class="col-md-8">

<h2><%= @page_title %></h2>

<p>Are you sure you want to permanetly delete this subject?</p>

<dl class="dl-horizontal">

    <dt>#</dt>
    <dd><%= @subject.position %></dd>

    <dt>Name</dt>
    <dd><%= @subject.name %></dd>

    <dt>Visible</dt>
    <dd><%= @subject.visible ? "Yes" : "No" %></dd>

    <dt>Pages</dt>
    <dd><%= pluralize(@subject.pages.size, 'Page') %></dd>

    <dt>Created</dt>
    <dd><%= @subject.created_at.to_s(:long) %></dd>

    <dt>Updated</dt>
    <dd><%= @subject.updated_at.to_s(:long) %></dd>

</dl>

<%= form_for(@subject, :method => "delete") do |f| %>
    <%= f.submit("Delete", :class => "btn btn-danger") %>
    <%= link_to("Cancel", subjects_path, :class => "btn btn-default") %>
<% end %>


</div>
</div>

app/views/subjects/edit.html.erb
<% @page_title = "Edit Subject" %>


<div class="row">
<div class="col-md-11">

    <h2><%= @page_title %></h2>

    <%= form_for(@subject, :html => {:class => "form-horizontal"}) do |f|%>

        <%= render(:partial => "form", :locals => {:f => f}) %>
        
        <div>
            <%= f.submit("Save", :class => "btn btn-primary") %>
            <%= link_to("Cancel", subjects_path, :class => "btn btn-default") %>
        </div>

    <% end %>

</div>
</div>

app/views/subjects/index.html.erb
<% @page_title = "Subjects" %>

<h2><%= @page_title %></h2>
<a href=<%= new_subject_path %> class="btn btn-primary" role="button">Add New</a>

<div class="row">

<table class="table table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Visible</th>
        <th>Pages</th>
        <th>Actions</th>
    </tr>
    </thead>

    <tbody>

    <% @subjects.each do |subject| %>
    <tr>
        <td><%= subject.position %></td>
        <td>
            <%= link_to(subject.name, subject_path(subject), :data => {:toggle => "tooltip", :placement => "top"}, :title => "Detail") %>
        </td>
        <td><%= status_tag(subject.visible) %></td>
        <td>
            <%= link_to(pluralize(subject.pages.size, 'Page'), pages_path(:subject_id => subject.id), :data => {:toggle => "tooltip", :placement => "top"}, :title => "Pages") %>
        </td>
        <td>
            <%= edit_button_for(edit_subject_path(subject)) %>
            
            <a href=<%= delete_subject_path(subject) %> class="btn btn-danger glyphicon glyphicon-trash" role="button" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Delete"></a>
        </td>
    </tr>
    <% end %>

    </tbody>
</table>

</div>

app/views/subjects/new.html.erb
<% @page_title = "Create Subject" %>


<div class="row">
<div class="col-md-11">

    <h2><%= @page_title %></h2>
    <%= form_for(@subject, :html => {:class => "form-horizontal"}) do |f|%>

        <%= render(:partial => "form", :locals => {:f => f})%>

        <div class="col-md-10 col-md-offset-2">
            <%= f.submit("Save", :class => "btn btn-primary") %>
            <%= link_to("Cancel", subjects_path, :class => "btn btn-default") %>
        </div>

    <% end %>

</div>
</div>

app/views/subjects/show.html.erb
<% @page_title = @subject.name %>

<div class="row">
<div class="col-md-8">

<h2><%= @page_title %></h2>

<dl class="dl-horizontal">

    <dt>#</dt>
    <dd><%= @subject.position %></dd>

    <dt>Name</dt>
    <dd><%= @subject.name %></dd>

    <dt>Visible</dt>
    <dd><%= @subject.visible ? "Yes" : "No" %></dd>

    <dt>Pages</dt>
    <dd><%= pluralize(@subject.pages.size, 'Page') %></dd>

    <dt>Created</dt>
    <dd><%= @subject.created_at.to_s(:long) %></dd>

    <dt>Updated</dt>
    <dd><%= @subject.updated_at.to_s(:long) %></dd>

</dl>

</div>
</div>