config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => "public_show"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages
  resources :sections
  resources :admin_users, :except => [:show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

    has_secure_password
    has_and_belongs_to_many :pages
    has_many :section_edits
    has_many :sections, :through => :section_edits

    EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
    FORBIDDEN_USERNAMES = ['littlebopeep','humptydumpty','marymary']

    validates :first_name, 
        :presence => true, 
        :length => { :maximum => 25 }

    validates :last_name, 
        :presence => true, 
        :length => { :maximum => 50 }

    validates :username, 
        :length => { :within => 8..25 }, 
        :uniqueness => true

    validates :email, 
        :presence => true, 
        :length => { :maximum => 100 }, 
        :format => EMAIL_REGEX, :confirmation => true

    validate :username_is_allowed
    validate :no_new_users_on_monday, :on => :create

    scope :sorted, lambda { order(:last_name, :first_name) }
    
    def name
        "#{first_name} #{last_name}"
    end
    
    private

    def username_is_allowed
        if FORBIDDEN_USERNAMES.include?(username)
        errors.add(:username, "has been restricted from use.")
        end
    end

    def no_new_users_on_monday
        if Time.now.wday == 1
        errors.add(:base, "No new users on Mondays.")
        end
    end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  layout "admin"
  before_action :confirm_logged_in

  def index
    @admin_users = AdminUser.sorted
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_user_params)
    if @admin_user.save
      flash[:notice] = "Admin user created successfully."
      redirect_to(admin_users_path)
    else
      render("new")
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update_attributes(admin_user_params)
      flash[:notice] = "Admin user updated successfully."
      redirect_to(admin_users_path)
    else
      render("edit")
    end
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    flash[:notice] = "Admin user destroyed successfully"
    redirect_to(admin_users_path)
  end
  
  private

  def admin_user_params
    params.require(:admin_user).permit(:first_name, :last_name, :email, :username, :password)
  end
  
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= error_messages_for(f.object) %>

 <div class="form-group">
    <%= f.label(:first_name, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.text_field(:first_name, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <%= f.label(:last_name, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.text_field(:last_name, :class => "form-control") %>
    </div>
</div>


 <div class="form-group">
    <%= f.label(:email, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.text_field(:email, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <%= f.label(:username, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.text_field(:username, :class => "form-control") %>
    </div>
</div>

 <div class="form-group">
    <%= f.label(:password, :class => "control-label col-md-2") %>
    <div class="col-md-10">
        <%= f.password_field(:password, :class => "form-control") %>
    </div>
</div>

app/views/admin_users/edit.html.erb
<% @page_title = "Edit Admin User" %>

<div class="row">
<div class="col-md-11">

    <h2><%= @page_title %></h2>

    <%= form_for(@admin_user, :html => {:class => "form-horizontal"}) do |f|%>

        <%= render(:partial => "form", :locals => {:f => f}) %>

        <div class="col-md-10 col-md-offset-2">
            <%= f.submit("Save", :class => "btn btn-primary") %>
            <%= link_to("Cancel", admin_users_path, :class => "btn btn-default") %>
        </div>

    <% end %>

</div>
</div>

app/views/admin_users/index.html.erb
<% @page_title = "Admin Users" %>


<h2><%= @page_title %></h2>
<a href=<%= new_admin_user_path %> class="btn btn-primary" role="button">Add New</a>

<div class="row">

<table class="table table-hover">
    <thead>
    <tr>
        <th>Username</th>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
    </tr>
    </thead>

    <tbody>

    <% @admin_users.each do |admin_user| %>
    <tr>
        <td><%= admin_user.username %></td>
        <td><%= admin_user.name %></td>
        <td><%= mail_to(admin_user.email) %></td>
        <td>
            <%= edit_button_for(edit_admin_user_path(admin_user)) %>
            <%= delete_button_for(admin_user) %>
        </td>
    </tr>
    <% end %>

    </tbody>
</table>

</div>

app/views/admin_users/new.html.erb
<% @page_title = "Create Admin User" %>

<div class="row">
<div class="col-md-11">

<h2><%= @page_title %></h2>

<%= form_for(@admin_user, :html => {:class => "form-horizontal"}) do |f|%>

    <%= render(:partial => "form", :locals => {:f => f}) %>

    <div class="col-md-10 col-md-offset-2">
        <%= f.submit("Save", :class => "btn btn-primary") %>
        <%= link_to("Cancel", admin_users_path, :class => "btn btn-default") %>
    </div>

<% end %>

</div>
</div>