config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => "public_show"

  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages
  resources :sections
  resources :admin_users, :except => [:show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<% subjects ||= [] %>
<% admin_area ||= false %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("S-CMS", root_path, :class => "navbar-brand") %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">

        <li><%= link_to("Home", root_path) %></li>

        <% if admin_area %>
          <li><%= link_to("Manage Content", subjects_path) %></li>
          <li><%= link_to("Manage Admin Users", admin_users_path) %></li>
        <% else %>
          <% subjects.each do |subject| %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= subject.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% subject.pages.visible.sorted.each do |page| %>
                  <li><%= link_to(page.name, public_show_path(page.permalink)) %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <% end %>

      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if session[:user_id] %>
          <% if admin_area %>
            <li><%= link_to("Public Area", root_path) %></li>
          <% else %>
            <li><%= link_to("Admin Area", subjects_path) %></li>
          <% end %>
          <li><%= link_to("Logout", access_logout_path) %></li>
        <% else %>
          <li><%= link_to("Login", access_login_path) %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Simple CMS: <%= @page_title || "Admin Area" %></title>
    <%= stylesheet_link_tag("application", :media => "all") %>
    <%= javascript_include_tag("application") %>
</head>
<body>
    <%= render(:partial => "layouts/navigation", :locals => { :subjects => @subjects, :admin_area => true }) %>
    
    <main class="container">
        <%= breadcrumb_for(@subject, @page, @section, @page_title) %>
        <% if flash[:notice] %>
            <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
        <% end %>
        <%= yield %>
    </main>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Simple CMS<%= ": #{@page_title}" if @page_title %></title>
    <%= stylesheet_link_tag("application", :media => "all") %>
    <%= javascript_include_tag("application") %>
</head>
<body>

    <%= render(:partial => "layouts/navigation", :locals => { :subjects => @subjects, :admin_area => false }) %>

    <main class="container">
        <%= yield %>
    </main>
    
</body>
</html>